### ISSUE TITLE
I find some error here..

### ISSUE THREAD

**Issue by Coder-X15** [sinanislekdemir/payton#22]
Nice project indeed... but I found some error here.

I tried running the 'scene' example in the examples folder , and it started properly but ended with an error saying some undefined function is being called. Here's the error description in my Python 3.7.1 console in Windows:
 Traceback (most recent call last):
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\payton\examples\basics\01_scene.py", line 4, in <module>
    scene.run()
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\payton\scene\scene.py", line 454, in run
    self.depth_map_fbo = glGenFramebuffers(1)
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\OpenGL\wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "C:\Users\hello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\OpenGL\platform\baseplatform.py", line 414, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool(glGenFramebuffers) before calling

I'd love to see this issue debugged. Also, please do clarify me if the mistake is on my part.

**Comment by Coder-X15** [comment]
Hello... No one here? I want my problem solved!! I am craving for it... :(

**Comment by sinanislekdemir** [comment]
Sorry for the delay, I hate the new github notification system. :) I'll reply you in about an hour!

**Comment by sinanislekdemir** [comment]
Okay, so here is the "probable" deal; @Coder-X15 
I never had a chance to try Payton in Windows before. I use Linux and Mac and those should be fine. But here is the catch. It seems like you are missing some core OpenGL 3.x functionality. Payton runs on OpenGL 3.3+.
I believe your graphics card or driver might not be supporting required version of OpenGL but to double-check you can use OpenGL Extension Viewer https://www.realtech-vr.com/home/glview 
As an example, Virtualbox guests can only support OpenGL 2.x not 3.x series.

Your error message is coming from OpenGL bindings (http://pyopengl.sourceforge.net/) not from the Payton library itself. :disappointed: 

Let me know about the OpenGL version and I really want to see the results on Windows :crossed_fingers: 
https://support.esri.com/en/technical-article/000011375

**Comment by Coder-X15** [comment]
Thanks for your kind attention, sir. You see, I am basically 15 years old and I am not that acquainted with graphic design, 3-D rendering or even game creation. Also, I thought of making a game using this tool of yours, and that's why I am following you.

Coming to the mains, I ran some tests on the OpenGL Extension Viewer and it said 'Not Compatible' at tests 4.4 and 4.5 . The maximum frames per second was shown at test 3.1 (for OpenGL API Version 4.3 - I think that's the build version, because the version was shown as '4.3.0 - Build 20.19.15.4703'). Also, alongside details about the graphics driver (Intel) it was given 'Check for updated drivers'). Below the 'Directx' label, the supported profiles was shown as 11.4 alongside an option to get the latest one. I tried getting it from the official Microsoft website, but on trying to set it up, the setup says that a newer version is already present in the system ( > 9.0c ).

Frankly, I didn't understand a bit of those details, but I believe that your guidance show me the way out. Please do help me when free.

Also, are you an Alan Walker fan ? I have been searching for his private email address so I can reach out to him with a secret plan ( Please don't make this post public [ a request to all those who view this forum or whatever]) , but with limited success. I got his phone number, his MER Mussik account email address and even that of a person who interviewed him, sent emails to all of them, but nothing came of it till now. I'd love to get hold of his attention as soon as possible, so I can get my plan working.... 

Thanks for all help in advance

Coder-X15 :)

**Comment by Coder-X15** [comment]
To know more about Alan Walker (full name: Alan Olav Walker):[https://en.wikipedia.org/wiki/Alan_Walker_(music_producer)](url)

**Comment by sinanislekdemir** [comment]
To be honest, as a 35 years old developer, I have absolutely no idea who Alan Walker is :D I grew up with Metallica, Ozzy, Megadeth, Motörhead, ACDC, Led Zeppelin etc. 

And also, I started around 15. My first programming language was QBasic but my early 3D attempts were with Dark Basic.

Coming back to the topic, can you try installing `PyOpenGL_accelerate` package?

`pip install PyOpenGL_accelerate`

Then try the same example again. If that resolves your problem, I will add that to the next release.

**Comment by sinanislekdemir** [comment]
I published a new version of Payton with the PyOpenGL_accelerate in the dependencies so just upgrading Payton would probably install it.

**Comment by Coder-X15** [comment]
I understand the fact that the error came from PyOpenGL, and also that the error must be on my side of things... for more details to get your help on the topic, here  are they:
1) I use a 64-bit Windows OS
2)My Python version is 3.7.1
3)4 GB DDR3 L memory
4)500 GB HDD
5)Intel Pentium 3556 processor (1.7 GHz, 2 MB L3 cache) (2 nos. , I think)
6)Intel HD Graphics (graphics driver)

I didn't check for the graphics card. I'll tell it if I get it. Please help me out of this problem. Remember, I am 15 and I am no dedicated gamer or graphics designer.

Thanks
Sam

**Comment by Coder-X15** [comment]
I am a child who is only about to enter the big universe of computer science...

**Comment by Coder-X15** [comment]
What keeps me attracted to this project is its ease of use. I feel that trying to build a 3D game engine using this will be a really great achievement.

**Comment by sinanislekdemir** [comment]
Personal opinion: Treat kids just like adults so they can grow up. And stop complaining about your age :) I worked with not one but two high-school kids as colleagues (both were frontend developers, we even celebrated their high-school diplomas) and I highly respect their talent still; 

I got it working under a crappy Virtualbox Windows 10. 256mb of graphics.
But I don't encourage the way I did it. So, I will just tell you how I got it working;
Here is the proof of it works. Also I did a new release to get it working. You should install payton 0.0.9 to get it working. I had to disable some shader verifications;

![Screenshot_20200611_093140](https://user-images.githubusercontent.com/1842484/84352875-cc702f80-abc6-11ea-8e52-a76098221e99.png)

So simply; I installed Mesa3D drivers. Google for what is Mesa3d :) 
https://github.com/pal1000/mesa-dist-win/releases/download/20.1.0/mesa3d-20.1.0-release-msvc.7z

> Mesa, also called Mesa3D and The Mesa 3D Graphics Library, is an open source software implementation of OpenGL, Vulkan, and other graphics API specifications. Mesa translates these specifications to vendor-specific graphics hardware drivers

So with the Mesa OpenGL drivers in-place, it can just work. But this installs new OpenGL drivers to your system so the risk is yours;

**Comment by Coder-X15** [comment]
Well I'll try it. Where should I put the drivers?

**Comment by sinanislekdemir** [comment]
No need to put it anywhere, there is a file called `systemwidedeploy.cmd` inside the archive. run it. it should copy all the needed stuff

**Comment by Coder-X15** [comment]
Sorry if I have caused you some problem. I am nowhere nearby your knowledge level so I suggest that you may (I am not sure) have to explain things to me. In things like these, I am no expert. And even if I have a bit of that knowledge, I can never match experts like you.

To tell you the truth, I have no idea of how 3D graphics can be made using Python or even of how to create games on Python. Also I am not that acquainted with things deep in the system. I am only trying to make a 3D  racing game for my young brother, who is really fond of those Need For Speed kind of racing games. It's a disadvantage for children like us to get games like these by buying. We rather prefer free games to paid ones.

**Comment by Coder-X15** [comment]
> No need to put it anywhere, there is a file called systemwidedeploy.cmd inside the archive. run it. it should copy all the needed stuff

You mean it is some sort of a batch file? Great then!

**Comment by Coder-X15** [comment]
Also, I consider making something myself is something really joyful for me..

**Comment by Coder-X15** [comment]
After I get hold of it, I should run the systemwidedeply.cmd file, right? Or any other steps?

**Comment by sinanislekdemir** [comment]
I get you :) my first computer had 1gb of hard-drive (I was lucky to have an hard-drive), 16mb of ram, 80386 cpu. so no games for me as well. that's how I started coding back then to entertain myself.

unfortunately, Python is not suitable for an actual game development. It is an interpreted language. Which means, the code you write on Python does not directly go to CPU but python.exe reads your code and runs relevant stuff on cpu for your code. So there is a man in the middle which makes things less performant.
But with Payton, you can teach yourself the essentials you need to know before jumping into real game development. Before you move into game development, you need to know programming, algorithms, basic 3D calculations, positions, vectors, matrix operations etc. So, you can use Payton as a playground for your future game and design your ideas on Payton. It won't work as fast as a real game but will do the trick.

If you want to get into game development but think C or C++ are just too hard to learn (which might be) you can try learning a webgl based library like Three JS or BabylonJS
They have more tools that you don't have to do yourself like Physics engines and demos;

https://threejs.org/examples/webgl_materials_car.html

for instance;

**Comment by sinanislekdemir** [comment]
> After I get hold of it, I should run the systemwidedeply.cmd file, right? Or any other steps?

no other steps. run the batch and try it. remember, you should upgrade Payton to latest version;

`pip install payton --upgrade`

**Comment by Coder-X15** [comment]
I upgraded the thing...
Pyinstaller can help you make standalone applications in your computer from Python code.
To get it, type the fllowing command in your console (I did it on Command Prompt in Windows):
'pip install pyinstaller`
Then, to convert the required file to an app:
1) Go to the folder where the file is (I suggest putting the source code subjected to conversion outside the folder containing Python projects, for ease of understanding) and Shift+Right click [For Windows] there.
2)Then you'll find an option to run either cmd or PowerShell from that folder ,in the menu that appears. Click on it.
3)On the PowerShell or cmd window  that comes, type:`pyinstaller <your file name here>.py` (Not only .py, but also .pyz and such other extensions are accepted)

And there you go ! You will get some folders out of which the 'dist' folder contains your standalone app ! Try putting that app on any Windows platform (if you're trying it on Windows) and see the results! (Make sure that if you're trying this on a x - bit (x is variable) system, the application when tested for compatibility is put in a similar x - bit system)

I'm not sure whether such an app will work on older versions of Windows.

**Comment by Coder-X15** [comment]
Please note: What I meant by 'I upgraded the thing' is that I upgraded Payton.

**Comment by Coder-X15** [comment]
That Ferrari was cooooooooooooooollllllllllll !!!!!

**Comment by sinanislekdemir** [comment]
Honestly, I am not a windows user for a very long time. I guess this issue was the first time that I touched Windows 10. The last windows version I used was XP :) which I used for gaming only. Also I never had to bundle a python script as a standalone app. Almost all *nix type of operating systems comes with python out-of-the-box. 

let me know if Payton started to work for you

**Comment by Coder-X15** [comment]
Well, that Mesa3D stuff is downloading slowly.

**Comment by Coder-X15** [comment]
Maybe it will take me some time.

**Comment by Coder-X15** [comment]
Currently 29.6 MB is ready.

**Comment by Coder-X15** [comment]
Gaaaaahhh!!! It is taking a lot of time.... Does it download fast when Wi -Fi is in full range?

**Comment by Coder-X15** [comment]
Google says that the file is 'Forbidden'. What should I do?

**Comment by sinanislekdemir** [comment]
What? Odd. Install 7zip to extract it 
https://www.7-zip.org/

**Comment by Coder-X15** [comment]
Not about extracting. My network was a bit dwindling and after a long time of showing '29.7 MB /32.9 MB' Google told me that the file was 'Forbidden'.

**Comment by Coder-X15** [comment]
But the same network speed was present throughout the download attempt. Only at 29.6 MB did I try to get closer to the Wi - Fi . Then I returned to my seat.

**Comment by sinanislekdemir** [comment]
I copied the file to my server, you can try downloading it from www.islekdemir.com/mesa3d-20.1.0-release-msvc.7z

**Comment by Coder-X15** [comment]
Ok... I'll try

**Comment by Coder-X15** [comment]
Hey, Windows Defender found a virus there!

**Comment by Coder-X15** [comment]
In the file, I suppose...

**Comment by sinanislekdemir** [comment]
How come? what does it say?

**Comment by Coder-X15** [comment]
It said that the virus came from your file (mesa3d.... (etc.) .7z). Not actually I virus - they say that it is a trojan horse!

**Comment by sinanislekdemir** [comment]
Okay give me a second, checking for the original maintainer

> It said that the virus came from your file (mesa3d.... (etc.) .7z). Not actually a virus - they say that it is a trojan horse!

**Comment by Coder-X15** [comment]
Here's the text from Defender:

`Remediation incomplete
Status: Failed
This thraet or app might not be completely remediated.

Threat detected: Trojan:Win32/Vigorf.A
Alert level: Severe
Date:6/11/2020 2:49 PM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker`

For the 'affected items' label, the file affected was given as:
./Downloads/mesa3d-20.1.0-release-msvc.7z (I am not giving the full path)

Also, before this two other threats came up which, when removed, had your file removed along with them.

**Comment by Coder-X15** [comment]
Not two... just one - the same trojan..

**Comment by sinanislekdemir** [comment]
Okay had the same message in virtualbox, cleaning the package now. I'll give you a safe link

**Comment by Coder-X15** [comment]
Thanks...

**Comment by Coder-X15** [comment]
Phew! I feel good now!

**Comment by Coder-X15** [comment]
The same problem came  up on trying to download NFS MW 2012 from an insecure website...

**Comment by sinanislekdemir** [comment]
Sorry, I unpacked and repacked and while repacking I guess I haven't chosen the "best compression" so the archive is bigger than before but server is faster so should be any trouble;

I also removed the old package from server and I'll inform the original package maintainer about the incident. 

www.islekdemir.com/clean_mesa3d-20.1.0-release-msvc.7z

is the new link;

and https://github.com/pal1000/mesa-dist-win/issues/38 is the ticket I created for the original maintainer

**Comment by Coder-X15** [comment]
91.8 MB ?! Well, okay.... I'll stay patient. I am currently attending the online classes conducted by my school, and that's why I am a bit impatient at the moment. (Don't worry, I am not busy :) )

**Comment by Coder-X15** [comment]
Wow! Now the thing is coming in faster...

**Comment by Coder-X15** [comment]
I got the thing!
Running the file you said...
It ran and quit...

**Comment by Coder-X15** [comment]
What next? Run the example?

**Comment by sinanislekdemir** [comment]
Okay, I suspect that when I cleaned the virus, it deleted the required libraries as well along with the trojan. So might have broken the mesa package actually. give me some time to think

**Comment by Coder-X15** [comment]
Ok... but I ran the test and the same error came up. Maybe due to the deletion of those requisites...

**Comment by Coder-X15** [comment]
No problem! Take your time, sir. After all, there's always a tomorrow.

**Comment by sinanislekdemir** [comment]
Okay, 
this is a long show and I haven't tried myself;
www.islekdemir.com/mesa3d-20.1.0-release-mingw.7z

can you try this package? it is from the original maintainer and just built with another C compiler. Windows Defender didn't complain. 
When you run the batch, select 1) Desktop..

**Comment by Coder-X15** [comment]
I am not sure ... lemme see.. 
The 91.8 MB Mesa package didn't work, I guess..

**Comment by Coder-X15** [comment]
I tried to run it, but the error still persists..

**Comment by Coder-X15** [comment]
Ok, don't keep burning your brain over the topic. Let's take a break and get back to work tomorrow, sir.

**Comment by Coder-X15** [comment]
Too much of exertion over something that can be solved easily is bad for health. I'll pray that you get it right.

**Comment by Coder-X15** [comment]
> Okay,
> this is a long shot and I haven't tried myself;
> [www.islekdemir.com/mesa3d-20.1.0-release-mingw.7z](http://www.islekdemir.com/mesa3d-20.1.0-release-mingw.7z)
> 
> can you try this package? it is from the original maintainer and just built with another C compiler. Windows Defender didn't complain.
> When you run the batch, select 1) Desktop..

Did you mean that I must extract the stuff to the Desktop?

**Comment by Coder-X15** [comment]
Or to the Python directory?

**Comment by sinanislekdemir** [comment]
well, sorry to hear that. seems like we are at a dead-end here. 

I can't help you on this topic any further as any suggestion will likely break your system completely and this problem directly related to your graphic cards capabilities.

Note for myself, Payton doesn't work with old Intel Graphics card on Windows 10. (Linux driver seems to support OpenGL 3.x upto a sufficient degree)

**Comment by Coder-X15** [comment]
Anyway, I am leaving now. Let's think over it tomorrow.

**Comment by sinanislekdemir** [comment]
I meant when you run the systemwidedeploy.cmd it shows you options of installing. 1) Desktop ... is the option you should be selecting to install it. You did that right?

**Comment by sinanislekdemir** [comment]
btw; can you mail me instead of this issue conversation? honestly it is super annoying, github issues shouldn't be used outside their topic :) 
sinan@islekdemir.com
